FROM ghcr.io/open-webui/open-webui:main

ENV ENV=prod
ENV PORT=8080
ENV OPENAI_API_BASE_URL=""
ENV OPENAI_API_KEY=""


ENV ENABLE_RAG=False
ENV ENABLE_IMAGE_GENERATION=False
ENV ENABLE_STT=False
ENV ENABLE_TTS=False
ENV ENABLE_AUTOCOMPLETE_GENERATION=False
ENV ENABLE_TITLE_GENERATION=False


ENV WEBUI_AUTH=True
ENV WORKERS=1

EXPOSE 8080
